[project]
name = "daily-gold"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
    "pandas>=2.2.2",
    "matplotlib>=3.9.0",
    "python-dotenv>=1.0.1"

]
